name: effort-aigi
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  # Python
  - python=3.9
  
  # CUDA support
  - cudatoolkit=11.3
  - cudnn=8.2.1
  
  # Core ML/DL packages
  - pytorch=1.12.0
  - torchvision=0.13.0
  - torchaudio=0.12.0
  
  # Scientific computing
  - numpy=1.21.5
  - scipy=1.7.3
  - pandas=1.4.2
  
  # Computer vision
  - opencv=4.6.0
  - pillow=9.0.1
  - scikit-image=0.19.2
  - imageio=2.9.0
  - dlib=19.24.0
  
  # Machine learning
  - scikit-learn=1.0.2
  
  # Utilities
  - tqdm=4.61.0
  - pyyaml=6.0
  - tensorboard=2.10.1
  - setuptools=59.5.0
  
  # Visualization
  - seaborn=0.11.2
  
  # pip packages
  - pip
  - pip:
    # Numpy pinned to prevent upgrades to 2.x
    - numpy==1.21.5
    
    # Image processing and augmentation
    - imgaug==0.4.0
    - albumentations==1.1.0
    - imutils==0.5.4
    
    # Deep learning frameworks and tools
    - efficientnet-pytorch==0.7.1
    - timm==0.6.12
    - segmentation-models-pytorch==0.3.2
    - torchtoolbox==0.1.8.2
    
    # Transformers and CLIP (pinned to compatible versions with PyTorch 1.12)
    - transformers==4.21.3
    - einops
    - loralib
    - git+https://github.com/openai/CLIP.git
    
    # Additional utilities
    - filterpy
    - simplejson
    - kornia
    - fvcore
